### ISSUE TITLE
Improvements of and documentation of the Gradle build

### ISSUE THREAD

**Issue by jjohannes** [hashgraph/hedera-sdk-java#1794]
This issue is a follow-up for the work done here: https://github.com/hashgraph/hedera-sdk-java/pull/1732
Each task should be converted to an issue and addressed separately. Tasks are aligned in a priority order.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1885
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1898
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1894
- [x] Introduce Guava fix, which should be in plugin in the future
- [x] Get rid of `mergeJar("com.google.code.findbugs:jsr305")`
- [x] Adjust the code style rules and tools to what its done in _hedera-services_ (e.g. remove sonar, introduce spotless, decide if we want to keep error prone etc.)
- [x] Revisit gradle setup in `tck` project
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1896
- [x] Add more docs for the Gradle build (`.kts` files, code comments)
- [x] Resolve duplication in constraints publishing (right now there is some duplication)
- [x] Add PR Check for the Android Example (that it builds)
- [x] Add more docs for the Gradle build (`.md` files, in particular for adding/modifying dependencies)
- [x] Review what SDK dependencies should be transitive: https://github.com/hashgraph/hedera-sdk-java/pull/1732#discussion_r1603375896 --> moved to https://github.com/hashgraph/hedera-sdk-java/issues/2180
- [ ] Revisit `Taskfile.yml` (maybe make it as gradle tasks)
```

**Comment by thenswan** [comment]
>I added the constraints publishing. Right now there is some duplication, but I am not sure at the moment how to best centralize this version. But as we use dependabot, we can maybe also rely on it updating all of them. I would like to think about that again as follow up so that we can get this PR finally in.

**Comment by thenswan** [comment]
Guava fix, which should be in plugin in the future
https://github.com/gradlex-org/extra-java-module-info
Issue: https://github.com/gradlex-org/extra-java-module-info/issues/129

**Comment by thenswan** [comment]
Reviewing what dependencies should be transitive: https://github.com/hashgraph/hedera-sdk-java/pull/1732#discussion_r1603375896

**Comment by thenswan** [comment]
Add building the Android example to the GH Actions pipeline.

**Comment by thenswan** [comment]
Revisit GH Actions names.

**Comment by thenswan** [comment]
Revisit `Taskfile.yml` (maybe make it as gradle tasks)

**Comment by jjohannes** [comment]
Related:
- Check which boxed can be ticked after https://github.com/hashgraph/hedera-sdk-java/pull/2033 is integrated
- Check what may already be documented through https://github.com/hiero-ledger/hiero-gradle-conventions/issues/6
