### ISSUE TITLE
Follow up on solution to query the mirror node for the account balance, account info, and contract info data

### ISSUE THREAD

**Issue by thenswan** [hashgraph/hedera-sdk-java#1815]
This issue is a follow up on a feature #1697 with a PR #1698

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1820
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1821
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1822
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1823
- [ ] https://github.com/hashgraph/hedera-sdk-java/issues/1824
```

**Comment by thenswan** [comment]
cc @agadzhalov and @SimiHunjan for review and questions

**Comment by SimiHunjan** [comment]
1. I agree these should not be marked as deprecated because we only replaced where we are getting the data from so that information is still available just coming from a different source in the background.
2. That make sense to me. As far as our discussions with @steven-sheehy on the mirror node team the rest API will not be returning this value for now 
3. Sounds good
4. Sounds good

Thank you for documenting a detailed outline of the changes pertaining the token balances changes.

**Comment by thenswan** [comment]
Thanks @SimiHunjan 

Couple of points/proposals (operational-wise):
- when we will get to it, I propose to make those points as separate issues to address them in separate PRs;
- other SDKs should be reviewed to address those points as well, if needed.

**Comment by SimiHunjan** [comment]
@thenswan I shared this issue with @RickyLB for reference for the Swift/Rust SDKs last week. I am assuming @svetoslav-nikol0v,  @0xivanov,  and @gsstoykov have reviewed this with you already. If not, let's review in our team meeting.

**Comment by thenswan** [comment]
Closing as done.
