### ISSUE TITLE
CODEOWNERS file is not optimal

### ISSUE THREAD

**Issue by thenswan** [hashgraph/hedera-sdk-java#1870]
**TODOs:**
- [x] `@hashgraph/hedera-sdk-java-maintainers` seems not working as @agadzhalov PR approvals not allowing to merge the PR in Java SDK *(maybe there is a similar situation in other SDKs?)* -- investigate what might be the reason.
- [x] Add @0xivanov to `@hashgraph/hedera-sdk-java-maintainers`.
- [x] Remove groups (leave `@hashgraph/hedera-sdk-java-maintainers` as this the current active working team):
  - `@hashgraph/hedera-sdk`
  - `@hashgraph/hedera-sdk-java-contributors`
(I don't understand why we need to have those, please let me know if I am missing something)
