### ISSUE TITLE
Epic: Migrate to Java 21

### ISSUE THREAD

**Issue by 0xivanov** [hashgraph/hedera-sdk-java#2075]
### Action items

- [x] Bump Java version to 21
- [ ] Deprecate async/reactive code
- [x] Leverage virtual threads (introduced in Project Loom) instead of traditional ExecutorService for gRPC communication.
- [x] Manual testing

**Comment by SimiHunjan** [comment]
@naydenovn should we start to review this one?

**Comment by naydenovn** [comment]
Hi, @SimiHunjan. We will discuss it together with @0xivanov and after all priorities are considered we could take it into the sprint.

**Comment by SimiHunjan** [comment]
thanks @naydenovn !
